In [1]:
#import the numpy
import numpy as np

In [2]:
first_numpy_array = np.array([2,3,4,5])

In [3]:
first_numpy_array

array([2, 3, 4, 5])

In [4]:
#To get zeros matrix
array_with_zeros = np.zeros((3,3))

In [5]:
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#to get ones matrix
array_with_ones = np.ones((3,3))

In [4]:
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
empty_array = np.empty((2,4))

In [6]:
empty_array

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.07110092e-321, 4.71980431e+164,
        2.12199579e-314]])

In [16]:
np_arange =np.arange(12)

In [17]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
#to reshape the matrix
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
#to get num b/w 1 to 8
np_linspce = np.linspace(1,8,5)

In [22]:
np_linspce

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [23]:
#for two dimenstional
np_2d= np.arange(15).reshape(3,5)

In [24]:
np_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
#for three dim
np_3d = np.arange(27).reshape(3,3,3)

In [26]:
np_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# Basic operation

In [30]:
np.add(3,6)

9

In [31]:
np.subtract(102,34)

68

In [7]:
np_array_wags = np.array([23,43,12,34])*15

In [8]:
np_array_wags

array([345, 645, 180, 510])

In [34]:
sum(np_array_wags)

1680

# comparison array

In [9]:
weekly_hrs = np.array([23,45,65,25,36])

In [10]:
weekly_hrs[weekly_hrs>40]

array([45, 65])

In [11]:
weekly_hrs[weekly_hrs!=40]

array([23, 45, 65, 25, 36])

# logical array

In [12]:
np.logical_and(weekly_hrs>20,weekly_hrs<45)

array([ True, False, False,  True,  True])

In [13]:
np.logical_not(weekly_hrs>45)

array([ True,  True, False,  True,  True])

# Indexing

In [14]:
cycling_trials = np.array([[12,43,23,54],[23,34,45,56]])

In [15]:
cycling_trials[0]

array([12, 43, 23, 54])

In [16]:
## ':' use to select all rows
cycling_trials[:,1]

array([43, 34])

In [17]:
cycling_trials[:,1:4]

array([[43, 23, 54],
       [34, 45, 56]])

### 

In [50]:
cycling_trials.shape

(2, 4)

# copy and views

In [51]:
brt_nyc = np.array(['vxysv','gsby','ndcj','cdhc','jbsh'])

In [52]:
brt2_nyc = brt_nyc

In [53]:
print(brt2_nyc)

['vxysv' 'gsby' 'ndcj' 'cdhc' 'jbsh']


In [54]:
brt2_nyc is brt_nyc

True

In [55]:
#shallow copy
view_brt_nyc= brt_nyc.view()

In [56]:
print(view_brt_nyc)

['vxysv' 'gsby' 'ndcj' 'cdhc' 'jbsh']


In [57]:
view_brt_nyc[0] = 'central park'

In [58]:
print(view_brt_nyc)

['centr' 'gsby' 'ndcj' 'cdhc' 'jbsh']


In [59]:
brt2_nyc

array(['centr', 'gsby', 'ndcj', 'cdhc', 'jbsh'], dtype='<U5')

In [60]:
#deep copy
copy_of_nyc_brt = brt_nyc.copy()

In [61]:
copy_of_nyc_brt is brt_nyc

False

In [62]:
#shows 'copy' data is not owned by dataset
copy_of_nyc_brt.base is brt_nyc

False

In [63]:
copy_of_nyc_brt[3]= 'centr'

In [64]:
print(copy_of_nyc_brt)

['centr' 'gsby' 'ndcj' 'centr' 'jbsh']


In [65]:
brt_nyc

array(['centr', 'gsby', 'ndcj', 'cdhc', 'jbsh'], dtype='<U5')

# mathematical operation

In [66]:
np_sqrt = np.sqrt([12,23,34,45])

In [67]:
np_sqrt

array([3.46410162, 4.79583152, 5.83095189, 6.70820393])

In [68]:
from numpy import pi

In [69]:
np.cos(0)

1.0

In [70]:
np.cos(pi)

-1.0

In [71]:
np.floor([1.2,2.5,3.8,3.2,7.8])

array([1., 2., 3., 3., 7.])

In [72]:
np.exp([0,1,2])

array([1.        , 2.71828183, 7.3890561 ])

# shape manipulation

In [18]:
new_cyclist_trials = np.array([[12,22,31,24,14,21],[23,21,24,25,26,29]])

In [19]:
#for flatten the dataset                                                                              check
new_cyclist_trials.ravel()

array([12, 22, 31, 24, 14, 21, 23, 21, 24, 25, 26, 29])

In [20]:
#reshhape the dataset
new_cyclist_trials.reshape(3,4)

array([[12, 22, 31, 24],
       [14, 21, 23, 21],
       [24, 25, 26, 29]])

In [23]:
new_cyclist_trials.resize(2,6)

In [24]:
new_cyclist_trials

array([[12, 22, 31, 24, 14, 21],
       [23, 21, 24, 25, 26, 29]])

In [25]:
np.hsplit(new_cyclist_trials,2)

[array([[12, 22, 31],
        [23, 21, 24]]),
 array([[24, 14, 21],
        [25, 26, 29]])]

In [26]:
a = np.arange(6)

In [27]:
c = np.reshape(a,(2,3))      #1d to 2d

In [28]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
d = np.reshape(c,c.shape +(1,))  #2d to 3d

In [30]:
d

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [31]:
e = np.reshape(d,(2,3))       # 3d to 2d

In [32]:
e

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
np.reshape(e,(6))

array([0, 1, 2, 3, 4, 5])

In [34]:
#
np.hsplit(new_cyclist_trials,2)

[array([[12, 22, 31],
        [23, 21, 24]]),
 array([[24, 14, 21],
        [25, 26, 29]])]

In [36]:

k = np.array([12,24])

In [37]:
l = np.array([27,48])

In [39]:
np.hstack((k,l))

array([12, 24, 27, 48])

# broadcasting

In [40]:
array_a = np.array([1,2,3,4,5])
array_b = np.array([.2,.3,.4,.5,.6])

In [41]:
array_a * array_b

array([0.2, 0.6, 1.2, 2. , 3. ])

In [42]:
array_a + array_b

array([1.2, 2.3, 3.4, 4.5, 5.6])

In [43]:
array_a/4


array([0.25, 0.5 , 0.75, 1.  , 1.25])

# transpose

In [44]:
test_score = np.array([[12,13,14,15],[23,24,25,26]])

In [45]:
test_score.transpose()

array([[12, 23],
       [13, 24],
       [14, 25],
       [15, 26]])

# Inverse and Trace

In [46]:
inverse_array = np.array([[12,13],[23,24]])

In [47]:
np.linalg.inv(inverse_array)                #inverse of given array

array([[-2.18181818,  1.18181818],
       [ 2.09090909, -1.09090909]])

In [48]:
trace_array = np.array([[12,13],[23,24]])

In [49]:
np.trace(inverse_array)                      #sum of diagonal

36